# Alembic Configuration File
[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(created_at)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the timestamp of when the migration was generated
# leave as `None` if timestamps should be in local time without timezone info
# string value is passed to the constructor of datetime.datetime
sqlalchemy.url = driver://user:password@localhost/dbname

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
